---
- name: Verify connectivity
  hosts: monitoring
  gather_facts: false
  tasks:
    - name: Verify SSH connection
      ansible.builtin.ping:
      tags:
        - always

- name: Deploy monitoring stack
  hosts: monitoring
  become: true
  roles:
    - role: monitoring
      tags:
        - monitoring
