---
- name: Enable and start monitoring services
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - prometheus
    - prometheus-node-exporter
    - grafana-server
